### ISSUE TITLE
The “fork numbers” selector on the page about trend data needs to be updated

### ISSUE THREAD

**Issue by zhenyong** [jaywcjlove/github-rank#24]
in `src/getTrending.ts`
```
node = $(item).find('svg[aria-label="repo-forked"].octicon.octicon-repo-forked');
```

Current situation on the ground:
![image](https://user-images.githubusercontent.com/4012276/80054528-10916d00-8552-11ea-8916-b0e9f9437bfe.png)

**Comment by jaywcjlove** [comment]
@zhenyong thx!
