### ISSUE TITLE
关于用户的email获取权限

### ISSUE THREAD

**Issue by pkl6612** [jaywcjlove/github-rank#3]
请问怎么获取用户的email和blog？client_id和client_secret是OAuth Apps的吗？

**Comment by jaywcjlove** [comment]
@pkl6612 是的，通过 `client_id` 和 `client_secret` 才能获取到邮箱地址

https://github.com/jaywcjlove/github-rank/blob/2c491c4d852bef17ac94ff6c8c4e375b0c976565/src/utils/index.ts#L36-L54

**Comment by pkl6612** [comment]
十分感谢你的回复。
我像下边链接获取到的用户数据中的email字段全部是null。
```
https://api.github.com/users/${username}?client_id=xxxx&client_secret=yyyy
```
这是否是因令牌错误造成的？
请问client_id和client_secret是否来自github网页的 `Settings / Developer settings / OAuth Apps`

**Comment by jaywcjlove** [comment]
@pkl6612 email 字段是需要用户授权才能获取。
