### ISSUE TITLE
Github数据源来自哪里？

### ISSUE THREAD

**Issue by harkue** [jaywcjlove/github-rank#42]
Github数据源来自哪里？

**Comment by jaywcjlove** [comment]
@harkue 数据来源于 GitHub API

https://github.com/jaywcjlove/github-rank/blob/8efb323133583c5c28f8332c81416576f33a4fdc/src/utils/index.ts#L48-L56

**Comment by harkue** [comment]
soga.   原来是通过Github API查询出来的。
