### ISSUE TITLE
数据不全？

### ISSUE THREAD

**Issue by Jannchie** [jaywcjlove/github-rank#45]
不太清楚这个排行榜是怎么抓取数据的，我感觉我应该大概能上榜，但是没有出现在榜单里。

**Comment by jaywcjlove** [comment]
@Jannchie 这个是 Github API 返回的数据 

https://github.com/jaywcjlove/github-rank/blob/418d852dbdc5f7401421e4624f89aec7dca62df0/src/utils/index.ts#L17-L22

https://api.github.com/search/users?q=followers:%3E1000%20location:China

`https://api.github.com/search/users?q=followers:>1000 location:China`

@Jannchie 你将你的位置设置在了日本，我的这个只有两个排名，一个`全球` 和`中国`的，看你 followers 是够中国排名。

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/100530558-9125f380-322e-11eb-9c86-80e7a77849a6.png)

**Comment by Jannchie** [comment]
原来如此，了解了
