### ISSUE TITLE
排名发生错乱

### ISSUE THREAD

**Issue by halfrost** [jaywcjlove/github-rank#46]
见下图，这是 2020-12-9 日的排名。图上灰色的用户的排名比较低，但是穿插到了榜单中。

![](https://user-images.githubusercontent.com/10825609/101586429-e1fece80-3a1c-11eb-8b9c-afb4bcc6bc85.png)

**Comment by jaywcjlove** [comment]
@halfrost 这个是 GitHub API返回的结果，我没有做任何处理，我比对了数据，API 返回的数据是错误的，过两天又好了。

**Comment by halfrost** [comment]
@jaywcjlove 哦哦。。明白了。那就不用管它，过几天自己就好了。谢谢大佬解答。
