### ISSUE TITLE
漏掉了一些用户?

### ISSUE THREAD

**Issue by timqian** [jaywcjlove/github-rank#5]
比如没有在中国区尾部找到我😜😂

awsome list, thanks for building this

**Comment by jaywcjlove** [comment]
@timqian 这数据是 GitHub API 拉出来的，你的 `ChongQing, China` 是不是刚加上去的？

**Comment by timqian** [comment]
改了一个了月吧, 不过今天刚看了一眼已经排不上了😅先close
