### ISSUE TITLE
怎么知道自己排多少？

### ISSUE THREAD

**Issue by OXOYO** [jaywcjlove/github-rank#6]
像这样[https://gitstar-ranking.com/OXOYO](https://gitstar-ranking.com/OXOYO)
![image](https://user-images.githubusercontent.com/5074207/68746734-2cecbd80-0634-11ea-931d-36d8d17d2b84.png)

**Comment by jaywcjlove** [comment]
@OXOYO 目前这个仓库智能看 500 以内的。

**Comment by OXOYO** [comment]
@jaywcjlove 了解，谢谢
