### ISSUE TITLE
排名中人名显示灰色的问题

### ISSUE THREAD

**Issue by fredgan** [jaywcjlove/github-rank#94]
看到排名中一些人的名字是灰色的，简单查了一下代码

```jsx
users.forEach(function(user, idx){ const isUnActive = ((Date.now() - new Date(user.updated_at || '')) / 86400000) > 100;
```

说的好像是不活跃的天数超过100天。

但是这个好像是有问题的，比如第二名  [Evan You yyx990803](https://github.com/yyx990803)  几乎每天都是活跃的，不应该是显示灰色的。

**Comment by jaywcjlove** [comment]
@fredgan Github API 拉出来的 updated_at 字段是有问题。早就发现了，但是无法解决。

**Comment by fredgan** [comment]
那不如把这段逻辑去掉，让人看着榜单灰色的名字感觉怪怪的，毕竟页面没有什么地方说明这个灰色的含义或者备注可能不准确。

**Comment by jaywcjlove** [comment]
@fredgan 有空我删除掉，欢迎 PR
