### ISSUE TITLE
人物bug?

### ISSUE THREAD

**Issue by yishuiwang** [jaywcjlove/github-rank#98]
![image](https://user-images.githubusercontent.com/73023694/197401524-2eae0302-07c5-4d40-a517-45ac9baf1742.png)

![image](https://user-images.githubusercontent.com/73023694/197401564-53fcf696-a02d-4fa2-ba23-c8dd32cce0e2.png)

在Golbal/ 类别下 Evan You 的 follow 为88k，而在China/ 类别下则是50k
在Golbal/ 类别下 Evan You 的 归属地为Singapore，而在China/ 类别下则是 New Jersey

**Comment by jaywcjlove** [comment]
@yishuiwang 我不确定是什么原因造成的 Global 下数据是正确的，回头有空我看看，如果你有空可以修复一下，睡觉，晚安 thx!

<img width="597" alt="image" src="https://user-images.githubusercontent.com/1680273/197402030-d0792303-3408-4e64-8ace-ada19098c7fe.png">

**Comment by jaywcjlove** [comment]
@yishuiwang 我找到原因了，尤大大将位置更改为`Singapore`，现在中国地区的 API 获取不到大大的数据了，我们的数据里面因为缓存了历史数据，所以在中国区列表大大的数据还存在，但是数据是他该位置之前的数据。

https://github.com/jaywcjlove/github-rank/blob/c417a434b8486bece31f60c904137f9b3553333e/src/utils/index.ts#L17-L22
